[project]
name = "mlwm-deployment"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.13"
dependencies = [
    "dask>=2025.4.1",
    "dotenv>=0.9.9",
    "ipdb>=0.13.13",
    "mllam-data-prep @ git+https://github.com/ealerskans/mllam-data-prep.git@dk-case-studies-with-global-dt",
    "numcodecs<0.12.0",
    "s3fs>=2025.3.2",
    "tqdm>=4.67.1",
    "universal-pathlib>=0.2.6",
    "zarr<3.0",
    "xarray>=2025",
    "mars_to_zarr @ git+https://github.com/observingClouds/mars_to_zarr.git@feature/global-dt",
    "neural-lam @ git+https://github.com/observingclouds/neural-lam.git@dk-case-studies-with-global-dt",
    "weather-model-graphs @ git+https://github.com/ealerskans/weather-model-graphs.git@decoding_mask",
    "ipykernel>=6.29.5",
    "cartopy>=0.24.1",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]


[build-system]
requires = ["setuptools>=61", "setuptools_scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
version_scheme = "post-release"

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
mlwm-deployment = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.dependencies]
gdal = ">=3.11.0,<4"
libgdal-grib = ">=3.11.0,<4"
pygrib = ">=2.1.6,<3"
